from nets.test_models import run_model_training, get_model
from nets.trainer_convergence import train as conv_train
from nets.trainer_images import train as image_train
from transformations.model_based import *
from transformations.transformation_utils import do_distribution_weight_init, do_distribution_gabor_init_channel, \
    do_kernel_normal_distribution_init, do_layer_normal_distribution_init

trained_models = {
    'CORnet-S_train_decoder': {'model_func': apply_generic, 'layers': ["decoder"]},
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_conv': {'model_func': apply_generic,
                                                      'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                      'V1.conv1': do_distribution_gabor_init,
                                                      'V1.conv2': do_distribution_gabor_init,
                                                      'V2.conv_input': do_kernel_normal_distribution_init,
                                                      'V2.skip': do_kernel_normal_distribution_init,
                                                      'V2.conv1': do_kernel_normal_distribution_init,
                                                      'V2.conv2': do_distribution_weight_init,
                                                      'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                      'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                      'dim_5': 1, 'comp_5': 5
                                                      },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_img': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_kernel_normal_distribution_init,
                                                     'V2.conv1': do_kernel_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5,
                                                     'images': 0.5
                                                     },
    'CORnet-S_train_gmk1_wmc2_kn3_kn4_ln5_wm6_ra': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_weight_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True
                                                    },
    # CORnet-S_train_gmk1_wmc2_kn3_kn4_ln5_wm6_batchnorm_init
    'CORnet-S_train_gmk1_wmc2_kn3_kn4_ln5_wm6_bi': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_weight_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True,
                                                    'bn_init': do_layer_normal_distribution_init
                                                    },
    'CORnet-S_train_gmk1_wmc2_kn3_kn4_bi': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_weight_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_kernel_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'dim_1': 1, 'comp_1': 8, 'batchnorm': True,
                                            'bn_init': do_layer_normal_distribution_init},
    'CORnet-S_train_gmk1_wmc2_kn3_kn4_ra': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_weight_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_kernel_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'dim_1': 1, 'comp_1': 8, 'batchnorm': True},
    'CORnet-S_train_gabor_dist_weight_dist_channel_bi': {'model_func': apply_generic,
                                                         'layers': ['V2', 'V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_weight_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'dim': 1, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init},
    'CORnet-S_train_gmk1_wmc2_kn3_bi': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4',
                                                   'IT', "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_weight_init,
                                        'V2.conv_input': do_kernel_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'dim_1': 1, 'comp_1': 8, 'batchnorm': True,
                                        'bn_init': do_layer_normal_distribution_init},
    'CORnet-S_train_gabor_dist_weight_dist_channel_ra': {'model_func': apply_generic,
                                                         'layers': ['V2', 'V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_weight_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'dim': 1, 'batchnorm': True},
    'CORnet-S_train_gmk1_wmc2_kn3_ra': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4',
                                                   'IT', "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_weight_init,
                                        'V2.conv_input': do_kernel_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'dim_1': 1, 'comp_1': 8, 'batchnorm': True,
                                        },
    'CORnet-S_train_gmk1_wmc2_ln3_bi': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4',
                                                   'IT', "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_weight_init,
                                        'V2.conv_input': do_layer_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'dim_1': 1, 'comp_1': 8, 'batchnorm': True,
                                        'bn_init': do_layer_normal_distribution_init},
    'CORnet-S_train_gmk1_wmc2_ln3_ra': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4',
                                                   'IT', "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_weight_init,
                                        'V2.conv_input': do_layer_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'dim_1': 1, 'comp_1': 8, 'batchnorm': True,
                                        },
    'CORnet-S_train_gabor_dist_both_kernel_ra': {'model_func': apply_generic,
                                                 'layers': ['V2', 'V4', 'IT', "decoder"],
                                                 'V1.conv1': do_distribution_gabor_init,
                                                 'V1.conv2': do_distribution_gabor_init,
                                                 'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                 'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                 'batchnorm': True,
                                                 },
    'CORnet-S_train_gabor_dist_both_kernel_bi': {'model_func': apply_generic,
                                                 'layers': ['V2', 'V4', 'IT', "decoder"],
                                                 'V1.conv1': do_distribution_gabor_init,
                                                 'V1.conv2': do_distribution_gabor_init,
                                                 'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                 'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                 'batchnorm': True,
                                                 'bn_init': do_layer_normal_distribution_init
                                                 },
    'CORnet-S_train_gabor_dist_kernel_gabor_dist_channel_ra': {'model_func': apply_generic,
                                                               'layers': ['V2', 'V4', 'IT', "decoder"],
                                                               'V1.conv1': do_distribution_gabor_init,
                                                               'V1.conv2': do_distribution_gabor_init_channel,
                                                               'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                               'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                               'batchnorm': True,
                                                               },
    'CORnet-S_train_gabor_dist_kernel_gabor_dist_channel_bi': {'model_func': apply_generic,
                                                               'layers': ['V2', 'V4', 'IT', "decoder"],
                                                               'V1.conv1': do_distribution_gabor_init,
                                                               'V1.conv2': do_distribution_gabor_init_channel,
                                                               'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                               'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                               'batchnorm': True,
                                                               'bn_init': do_layer_normal_distribution_init
                                                               },
    'CORnet-S_train_gmk1_gmk2_kn3_bi': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                   "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_gabor_init,
                                        'V2.conv_input': do_kernel_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                        'batchnorm': True,
                                        'bn_init': do_layer_normal_distribution_init
                                        },
    'CORnet-S_train_gmk1_gmk2_kn3_ra': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                   "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_gabor_init,
                                        'V2.conv_input': do_kernel_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                        'batchnorm': True,
                                        },
    'CORnet-S_train_gmk1_gmk2_ln3_bi': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                   "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_gabor_init,
                                        'V2.conv_input': do_layer_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                        'batchnorm': True,
                                        'bn_init': do_layer_normal_distribution_init
                                        },
    'CORnet-S_train_gmk1_gmk2_ln3_ra': {'model_func': apply_generic,
                                        'layers': ['V2.skip', 'V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                   "decoder"],
                                        'V1.conv1': do_distribution_gabor_init,
                                        'V1.conv2': do_distribution_gabor_init,
                                        'V2.conv_input': do_layer_normal_distribution_init,
                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                        'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                        'batchnorm': True,
                                        },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_ra': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_kernel_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_bi': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_kernel_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            'bn_init': do_layer_normal_distribution_init
                                            },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_ra': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_layer_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_bi': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_kernel_normal_distribution_init,
                                            'V2.skip': do_layer_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            'bn_init': do_layer_normal_distribution_init
                                            },
    'CORnet-S_train_gmk1_gmk2_ln3_ln4_bi': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_layer_normal_distribution_init,
                                            'V2.skip': do_layer_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            'bn_init': do_layer_normal_distribution_init
                                            },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_bi': {'model_func': apply_generic,
                                            'layers': ['V2.conv1', 'V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                       "decoder"],
                                            'V1.conv1': do_distribution_gabor_init,
                                            'V1.conv2': do_distribution_gabor_init,
                                            'V2.conv_input': do_layer_normal_distribution_init,
                                            'V2.skip': do_kernel_normal_distribution_init,
                                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                            'batchnorm': True,
                                            'bn_init': do_layer_normal_distribution_init
                                            },
    'CORnet-S_train_gmk1_gmk2_ln3_ln4_ln5_ra': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_layer_normal_distribution_init,
                                                'V2.skip': do_layer_normal_distribution_init,
                                                'V2.conv1': do_layer_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_ra': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_kernel_normal_distribution_init,
                                                'V2.skip': do_kernel_normal_distribution_init,
                                                'V2.conv1': do_kernel_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                },
    'CORnet-S_train_gmk1_gmk2_ln3_ln4_ln5_bi': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_layer_normal_distribution_init,
                                                'V2.skip': do_layer_normal_distribution_init,
                                                'V2.conv1': do_layer_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                'bn_init': do_layer_normal_distribution_init
                                                },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_bi': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_kernel_normal_distribution_init,
                                                'V2.skip': do_kernel_normal_distribution_init,
                                                'V2.conv1': do_kernel_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                'bn_init': do_layer_normal_distribution_init
                                                },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_kn5_bi': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_kernel_normal_distribution_init,
                                                'V2.skip': do_layer_normal_distribution_init,
                                                'V2.conv1': do_kernel_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                'bn_init': do_layer_normal_distribution_init
                                                },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_ln5_bi': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_kernel_normal_distribution_init,
                                                'V2.skip': do_layer_normal_distribution_init,
                                                'V2.conv1': do_layer_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                'bn_init': do_layer_normal_distribution_init
                                                },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_bi': {'model_func': apply_generic,
                                                'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                           "decoder"],
                                                'V1.conv1': do_distribution_gabor_init,
                                                'V1.conv2': do_distribution_gabor_init,
                                                'V2.conv_input': do_layer_normal_distribution_init,
                                                'V2.skip': do_kernel_normal_distribution_init,
                                                'V2.conv1': do_layer_normal_distribution_init,
                                                'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                'batchnorm': True,
                                                'bn_init': do_layer_normal_distribution_init
                                                },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_ln5_wm6_ra': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True
                                                    },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_ln5_wm6_bi': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True,
                                                    'bn_init': do_layer_normal_distribution_init
                                                    },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_bi': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_kernel_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True,
                                                    'bn_init': do_layer_normal_distribution_init
                                                    },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_ra': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_kernel_normal_distribution_init,
                                                    'V2.skip': do_kernel_normal_distribution_init,
                                                    'V2.conv1': do_kernel_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True,
                                                    },
    'CORnet-S_train_gmk1_gmk2_ln3_ln4_ln5_wm6_ra': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_layer_normal_distribution_init,
                                                    'V2.skip': do_layer_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True
                                                    },
    'CORnet-S_train_gmk1_gmk2_ln3_ln4_ln5_wm6_bi': {'model_func': apply_generic,
                                                    'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                    'V1.conv1': do_distribution_gabor_init,
                                                    'V1.conv2': do_distribution_gabor_init,
                                                    'V2.conv_input': do_layer_normal_distribution_init,
                                                    'V2.skip': do_layer_normal_distribution_init,
                                                    'V2.conv1': do_layer_normal_distribution_init,
                                                    'V2.conv2': do_distribution_weight_init,
                                                    'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                    'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                    'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                    'batchnorm': True,
                                                    'bn_init': do_layer_normal_distribution_init
                                                    },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_kn5_wmc6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_layer_normal_distribution_init,
                                                     'V2.conv1': do_kernel_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_ln5_wmc6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_layer_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_ln5_wmk6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_layer_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5, 'dim_1': 0, 'comp_1': 8,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_test': {'model_func': apply_generic,
                            'layers': ['V2.conv3', 'V4', 'IT',
                                       "decoder"],
                            'V1.conv1': do_distribution_gabor_init,
                            'V1.conv2': do_distribution_gabor_init,
                            'V2.conv_input': do_kernel_normal_distribution_init,
                            'V2.skip': do_layer_normal_distribution_init,
                            'V2.conv1': do_layer_normal_distribution_init,
                            'V2.conv2': do_distribution_weight_init,
                            'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                            'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                            'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                            'batchnorm': True,
                            'bn_init': do_layer_normal_distribution_init
                            },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wmk6_kn7_bi': {'model_func': apply_generic,
                                                         'layers': ['V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_gabor_init,
                                                         'V2.conv_input': do_kernel_normal_distribution_init,
                                                         'V2.skip': do_kernel_normal_distribution_init,
                                                         'V2.conv1': do_kernel_normal_distribution_init,
                                                         'V2.conv2': do_distribution_weight_init,
                                                         'V2.conv3': do_kernel_normal_distribution_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                         'dim_5': 0, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init
                                                         },
    'CORnet-S_train_gmk1_gmk2_kn3_kn4_ln5_wm6_bi_mom': {'model_func': apply_generic,
                                                        'layers': ['V2.conv3', 'V4', 'IT', "decoder"],
                                                        'V1.conv1': do_distribution_gabor_init,
                                                        'V1.conv2': do_distribution_gabor_init,
                                                        'V2.conv_input': do_kernel_normal_distribution_init,
                                                        'V2.skip': do_kernel_normal_distribution_init,
                                                        'V2.conv1': do_layer_normal_distribution_init,
                                                        'V2.conv2': do_distribution_weight_init,
                                                        'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                        'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                        'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                        'batchnorm': True,
                                                        'bn_init': do_layer_normal_distribution_init,
                                                        'momentum': True
                                                        },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmc6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_layer_normal_distribution_init,
                                                     'V2.skip': do_kernel_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmk6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_layer_normal_distribution_init,
                                                     'V2.skip': do_kernel_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 0, 'comp_5': 5,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmc6_kn7_bi': {'model_func': apply_generic,
                                                         'layers': ['V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_gabor_init,
                                                         'V2.conv_input': do_layer_normal_distribution_init,
                                                         'V2.skip': do_kernel_normal_distribution_init,
                                                         'V2.conv1': do_layer_normal_distribution_init,
                                                         'V2.conv2': do_distribution_weight_init,
                                                         'V2.conv3': do_kernel_normal_distribution_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                         'dim_5': 1, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init
                                                         },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmc6_ln7_bi': {'model_func': apply_generic,
                                                         'layers': ['V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_gabor_init,
                                                         'V2.conv_input': do_layer_normal_distribution_init,
                                                         'V2.skip': do_kernel_normal_distribution_init,
                                                         'V2.conv1': do_layer_normal_distribution_init,
                                                         'V2.conv2': do_distribution_weight_init,
                                                         'V2.conv3': do_layer_normal_distribution_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                         'dim_5': 1, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init
                                                         },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmk6_kn7_bi': {'model_func': apply_generic,
                                                         'layers': ['V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_gabor_init,
                                                         'V2.conv_input': do_layer_normal_distribution_init,
                                                         'V2.skip': do_kernel_normal_distribution_init,
                                                         'V2.conv1': do_layer_normal_distribution_init,
                                                         'V2.conv2': do_distribution_weight_init,
                                                         'V2.conv3': do_kernel_normal_distribution_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                         'dim_5': 0, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init
                                                         },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_wmk6_ln7_bi': {'model_func': apply_generic,
                                                         'layers': ['V4', 'IT', "decoder"],
                                                         'V1.conv1': do_distribution_gabor_init,
                                                         'V1.conv2': do_distribution_gabor_init,
                                                         'V2.conv_input': do_layer_normal_distribution_init,
                                                         'V2.skip': do_kernel_normal_distribution_init,
                                                         'V2.conv1': do_layer_normal_distribution_init,
                                                         'V2.conv2': do_distribution_weight_init,
                                                         'V2.conv3': do_layer_normal_distribution_init,
                                                         'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                         'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                         'dim_5': 0, 'batchnorm': True,
                                                         'bn_init': do_layer_normal_distribution_init
                                                         },
    'CORnet-S_train_wmk0_wmc1_bi': {'model_func': apply_generic,
                                    'layers': ['V2', 'V4', 'IT', "decoder"],
                                    'V1.conv1': do_distribution_weight_init,
                                    'V1.conv2': do_distribution_weight_init,
                                    'batchnorm': True,
                                    'bn_init': do_layer_normal_distribution_init,
                                    'dim_0': 0, 'dim_1': 1,
                                    },
    'CORnet-S_train_wmc0_wmc1_bi': {'model_func': apply_generic,
                                    'layers': ['V2', 'V4', 'IT', "decoder"],
                                    'V1.conv1': do_distribution_weight_init,
                                    'V1.conv2': do_distribution_weight_init,
                                    'batchnorm': True,
                                    'bn_init': do_layer_normal_distribution_init,
                                    'dim_0': 1, 'dim_1': 1,
                                    },
    'CORnet-S_train_kn1_kn2_bi': {'model_func': apply_generic,
                                  'layers': ['V2', 'V4', 'IT', "decoder"],
                                  'V1.conv1': do_kernel_normal_distribution_init,
                                  'V1.conv2': do_kernel_normal_distribution_init,
                                  'batchnorm': True,
                                  'bn_init': do_layer_normal_distribution_init
                                  },
    'CORnet-S_train_ln1_ln2_bi': {'model_func': apply_generic,
                                  'layers': ['V2', 'V4', 'IT', "decoder"],
                                  'V1.conv1': do_layer_normal_distribution_init,
                                  'V1.conv2': do_layer_normal_distribution_init,
                                  'batchnorm': True,
                                  'bn_init': do_layer_normal_distribution_init
                                  },
    'CORnet-S_train_gabor_dist_both_kernel_bi_full': {'model_func': apply_generic,
                                                      'layers': ['V2', 'V4', 'IT', "decoder"],
                                                      'V1.conv1': do_distribution_gabor_init,
                                                      'V1.conv2': do_distribution_gabor_init,
                                                      'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                      'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                      'batchnorm': True, 'full': True,
                                                      'bn_init': do_layer_normal_distribution_init,
                                                      },
    'CORnet-S_train_gmk1_gmk2_ln3_kn4_ln5_bi_full': {'model_func': apply_generic,
                                                     'layers': ['V2.conv2', 'V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_gabor_init,
                                                     'V1.conv2': do_distribution_gabor_init,
                                                     'V2.conv_input': do_layer_normal_distribution_init,
                                                     'V2.skip': do_kernel_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                     'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                     'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                     'batchnorm': True, 'full': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_gmk1_gmk2_kn3_ln4_ln5_wmc6_bi_full': {'model_func': apply_generic,
                                                          'layers': ['V2.conv3', 'V4', 'IT',
                                                                     "decoder"],
                                                          'V1.conv1': do_distribution_gabor_init,
                                                          'V1.conv2': do_distribution_gabor_init,
                                                          'V2.conv_input': do_kernel_normal_distribution_init,
                                                          'V2.skip': do_layer_normal_distribution_init,
                                                          'V2.conv1': do_layer_normal_distribution_init,
                                                          'V2.conv2': do_distribution_weight_init,
                                                          'file': '/braintree/home/fgeiger/weight_initialization/gabors_tiago_scaled_cornet_2.npy',
                                                          'file_1': '/braintree/home/fgeiger/weight_initialization/gabors_conv2.npy',
                                                          'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                          'batchnorm': True, 'full': True,
                                                          'bn_init': do_layer_normal_distribution_init
                                                          },
    'CORnet-S_train_kn1_kn2_kn3_ln4_ln5_wmc6_bi': {'model_func': apply_generic,
                                                   'layers': ['V2.conv3', 'V4', 'IT',
                                                              "decoder"],
                                                   'V1.conv1': do_kernel_normal_distribution_init,
                                                   'V1.conv2': do_kernel_normal_distribution_init,
                                                   'V2.conv_input': do_kernel_normal_distribution_init,
                                                   'V2.skip': do_layer_normal_distribution_init,
                                                   'V2.conv1': do_layer_normal_distribution_init,
                                                   'V2.conv2': do_distribution_weight_init,
                                                   'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                   'batchnorm': True,
                                                   'bn_init': do_layer_normal_distribution_init
                                                   },
    'CORnet-S_train_wmc1_wmc2_kn3_ln4_ln5_wmc6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_weight_init,
                                                     'V1.conv2': do_distribution_weight_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_layer_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'dim_0': 1, 'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_wmk1_wmk2_kn3_ln4_ln5_wmc6_bi': {'model_func': apply_generic,
                                                     'layers': ['V2.conv3', 'V4', 'IT',
                                                                "decoder"],
                                                     'V1.conv1': do_distribution_weight_init,
                                                     'V1.conv2': do_distribution_weight_init,
                                                     'V2.conv_input': do_kernel_normal_distribution_init,
                                                     'V2.skip': do_layer_normal_distribution_init,
                                                     'V2.conv1': do_layer_normal_distribution_init,
                                                     'V2.conv2': do_distribution_weight_init,
                                                     'dim_0': 0, 'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                     'batchnorm': True,
                                                     'bn_init': do_layer_normal_distribution_init
                                                     },
    'CORnet-S_train_kn1_kn2_kn3_kn4_kn5_wmc6_bi': {'model_func': apply_generic,
                                                   'layers': ['V2.conv3', 'V4', 'IT',
                                                              "decoder"],
                                                   'V1.conv1': do_kernel_normal_distribution_init,
                                                   'V1.conv2': do_kernel_normal_distribution_init,
                                                   'V2.conv_input': do_kernel_normal_distribution_init,
                                                   'V2.skip': do_kernel_normal_distribution_init,
                                                   'V2.conv1': do_kernel_normal_distribution_init,
                                                   'V2.conv2': do_distribution_weight_init,
                                                   'dim_5': 1, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                   'batchnorm': True,
                                                   'bn_init': do_layer_normal_distribution_init
                                                   },
    'CORnet-S_train_kn1_kn2_kn3_kn4_kn5_kn6_bi': {'model_func': apply_generic,
                                                  'layers': ['V2.conv3', 'V4', 'IT',
                                                             "decoder"],
                                                  'V1.conv1': do_kernel_normal_distribution_init,
                                                  'V1.conv2': do_kernel_normal_distribution_init,
                                                  'V2.conv_input': do_kernel_normal_distribution_init,
                                                  'V2.skip': do_kernel_normal_distribution_init,
                                                  'V2.conv1': do_kernel_normal_distribution_init,
                                                  'V2.conv2': do_kernel_normal_distribution_init,
                                                  'batchnorm': True,
                                                  'bn_init': do_layer_normal_distribution_init
                                                  },
    'CORnet-S_train_kn1_kn2_kn3_ln4_ln5_wmk6_bi': {'model_func': apply_generic,
                                                   'layers': ['V2.conv3', 'V4', 'IT',
                                                              "decoder"],
                                                   'V1.conv1': do_kernel_normal_distribution_init,
                                                   'V1.conv2': do_kernel_normal_distribution_init,
                                                   'V2.conv_input': do_kernel_normal_distribution_init,
                                                   'V2.skip': do_layer_normal_distribution_init,
                                                   'V2.conv1': do_layer_normal_distribution_init,
                                                   'V2.conv2': do_distribution_weight_init,
                                                   'dim_5': 0, 'comp_5': 5, 'dim_1': 1, 'comp_1': 8,
                                                   'batchnorm': True,
                                                   'bn_init': do_layer_normal_distribution_init
                                                   },
    'CORnet-S_train_kn1_kn2_kn3_kn4_kn5_kn6_kn7_bi': {'model_func': apply_generic,
                                                      'layers': ['V4', 'IT',
                                                                 "decoder"],
                                                      'V1.conv1': do_kernel_normal_distribution_init,
                                                      'V1.conv2': do_kernel_normal_distribution_init,
                                                      'V2.conv_input': do_kernel_normal_distribution_init,
                                                      'V2.skip': do_kernel_normal_distribution_init,
                                                      'V2.conv1': do_kernel_normal_distribution_init,
                                                      'V2.conv2': do_kernel_normal_distribution_init,
                                                      'V2.conv3': do_kernel_normal_distribution_init,
                                                      'batchnorm': True,
                                                      'bn_init': do_layer_normal_distribution_init
                                                      },

}

v4 = {
    'CORnet-S_brain_kn8_kn9_kn10_wmk11_kn12_bi': {
        'layers': ['IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_distribution_weight_init,
        'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 0},
    'CORnet-S_brain_kn8_kn9_kn10_wmc11_kn12_bi': {
        'layers': ['IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_distribution_weight_init,
        'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 1},  #
    'CORnet-S_brain_kn8_kn9_kn10_wmk11_kn12_tr_bi': {
        'layers': ['V2.conv3', 'V4.conv3', 'IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_distribution_weight_init,
        'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 0},
    'CORnet-S_brain_kn8_kn9_kn10_wmc11_kn12_tr_bi': {
        'layers': ['V2.conv3', 'V4.conv3', 'IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_distribution_weight_init,
        'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 1},  #
    'CORnet-S_brain_kn8_kn9_kn10_wmc11_bi': {
        'layers': ['V4.conv3', 'IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_distribution_weight_init,
        # 'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 1,
    },
    'CORnet-S_brain2_kn8_kn9_kn10_kn11_bi': {
        'layers': ['V4.conv3', 'IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_kernel_normal_distribution_init,
        # 'V4.conv3': do_kernel_normal_distribution_init,
        'dim_10': 1,
    },
    'CORnet-S_brain2_kn8_kn9_kn10_kn11_kn12_bi': {
        'layers': ['IT', 'decoder'],
        'V4.conv_input': do_kernel_normal_distribution_init,
        'V4.skip': do_kernel_normal_distribution_init,
        'V4.conv1': do_kernel_normal_distribution_init,
        'V4.conv2': do_kernel_normal_distribution_init,
        'V4.conv3': do_kernel_normal_distribution_init,
    }

}


def get_config(model):
    if model not in trained_models:
        assert model in v4
        if model.split('_')[1] == 'brain':
            config = trained_models['CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_kn7_bi']
        elif model.split('_')[1] == 'brain2':
            config = trained_models['CORnet-S_train_kn1_kn2_kn3_kn4_kn5_kn6_kn7_bi']
        else:
            config = trained_models['CORnet-S_train_gmk1_wmc2_kn3_kn4_kn5_wmc6_kn7_v2']
        return {**config, **v4[model]}
    else:
        return trained_models[model]


# g = gabor, n=normal distribution, c=channel, k =kernel, w=weights, m= mixture, l=layer, j = jumbler, bd =best distribution
def train_model(model, train_func=None):
    config = get_config(model)
    if 'convergence' in config:
        train_func = conv_train
    if 'images' in config:
        trainer_images.image_load = config['images']
        print(f'We train with only {config["images"]} of images!')
        train_func = image_train
    net = get_model(model, False, config)
    run_model_training(model=net, identifier=model, config=config, train_func=train_func)


if __name__ == '__main__':
    model = 'CORnet-S_brain2_kn8_kn9_kn10_kn11_kn12_bi'
    # model = 'CORnet-S_train_gmk1_gmk2_kn3_kn4_kn5_wm6_2_gpu'
    # model = 'CORnet-S_train_gabor_dist_both_kernel'
    model = get_model(model, False, get_config(model))
    assert model is not None
